NUVOLAR_Excercise/force-app/main/default/objects/NV_obj_airport__c/NV_obj_airport__c.object-meta.xml
<CustomObject>
    <description>Object which stores airport related data.</description>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NUVOLAR_Excercise/force-app/main/default/objects/NV_obj_airport__c/fields/NV_fld_airportIATA__c.field-meta.xml
<CustomField>
    <fullName>NV_fld_airportIATA__c</fullName>
    <label>Airport IATA</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

NUVOLAR_Excercise/force-app/main/default/objects/NV_obj_airport__c/fields/NV_fld_airportLatitude__c.field-meta.xml
<CustomField>
    <fullName>NV_fld_airportLatitude__c</fullName>
    <label>Aiport Latitude</label>
    <precision>9</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

NUVOLAR_Excercise/force-app/main/default/objects/NV_obj_airport__c/fields/NV_fld_airportLongitude__c.field-meta.xml
<CustomField>
    <fullName>NV_fld_airportLongitude__c</fullName>
    <label>Airport Longitude</label>
    <precision>10</precision>
    <required>true</required>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

NUVOLAR_Excercise/force-app/main/default/classes/NV_cls_controller_test.cls
/**
 * @description       : Test class to test the different test scenarios.
 * @author            : IULIAN PREDA VLASCEANU
 * @group             :
 * @last modified on  : 27-01-2024
 * @last modified by  : IULIAN PREDA VLASCEANU
 **/
@isTest
public class NV_cls_controller_test{
    /**
    * @description Setup method of the class.
    * @author IULIAN PREDA VLASCEANU | 27-01-2024 
    **/
    @TestSetup
    static void makeData(){
        NV_obj_airport__c airport1 = new NV_obj_airport__c();
        airport1.Name = NV_cls_utils.NAME_1;
        airport1.NV_fld_airportIATA__c = NV_cls_utils.NAME_1;
        airport1.NV_fld_airportLongitude__c = NV_cls_utils.DEC_LONG_1;
        airport1.NV_fld_airportLatitude__c = NV_cls_utils.DEC_LAT_1;
        insert airport1;
    }

}